In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('/content/wine_fraud.csv')

In [ ]:
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4              0.70         0.00             1.9      0.076   
1               7.8              0.88         0.00             2.6      0.098   
2               7.8              0.76         0.04             2.3      0.092   
3              11.2              0.28         0.56             1.9      0.075   
4               7.4              0.70         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
6492            6.2              0.21         0.29             1.6      0.039   
6493            6.6              0.32         0.36             8.0      0.047   
6494            6.5              0.24         0.19             1.2      0.041   
6495            5.5              0.29         0.30             1.1      0.022   
6496            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
6492                 24.0                  92.0  0.99114  3.27       0.50   
6493                 57.0                 168.0  0.99490  3.15       0.46   
6494                 30.0                 111.0  0.99254  2.99       0.46   
6495                 20.0                 110.0  0.98869  3.34       0.38   
6496                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol quality   type  
0         9.4   Legit    red  
1         9.8   Legit    red  
2         9.8   Legit    red  
3         9.8   Legit    red  
4         9.4   Legit    red  
...       ...     ...    ...  
6492     11.2   Legit  white  
6493      9.6   Legit  white  
6494      9.4   Legit  white  
6495     12.8   Legit  white  
6496     11.8   Legit  white  

[6497 rows x 13 columns]

In [ ]:
X = df.drop('quality',axis=1)
y = df['quality']

In [ ]:
encoder = LabelEncoder() 
X['type'] = encoder.fit_transform(X['type'])

In [ ]:
X

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4              0.70         0.00             1.9      0.076   
1               7.8              0.88         0.00             2.6      0.098   
2               7.8              0.76         0.04             2.3      0.092   
3              11.2              0.28         0.56             1.9      0.075   
4               7.4              0.70         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
6492            6.2              0.21         0.29             1.6      0.039   
6493            6.6              0.32         0.36             8.0      0.047   
6494            6.5              0.24         0.19             1.2      0.041   
6495            5.5              0.29         0.30             1.1      0.022   
6496            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
6492                 24.0                  92.0  0.99114  3.27       0.50   
6493                 57.0                 168.0  0.99490  3.15       0.46   
6494                 30.0                 111.0  0.99254  2.99       0.46   
6495                 20.0                 110.0  0.98869  3.34       0.38   
6496                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  type  
0         9.4     0  
1         9.8     0  
2         9.8     0  
3         9.8     0  
4         9.4     0  
...       ...   ...  
6492     11.2     1  
6493      9.6     1  
6494      9.4     1  
6495     12.8     1  
6496     11.8     1  

[6497 rows x 12 columns]

## Feature Selection with Chi Square

In [ ]:
from sklearn.feature_selection import chi2
from sklearn.feature_selection import SelectKBest

In [ ]:

# k = 4 tells four top features to be selected
# Score function Chi2 tells the feature to be selected using Chi Square
test = SelectKBest(score_func=chi2, k=4)
fit = test.fit(X, y)
fit.scores_

array([7.18727644e-01, 1.18552395e+01, 1.64369707e+00, 6.42180788e+01,
       1.69351768e-01, 4.86716943e+02, 2.22820658e+02, 1.57006382e-05,
       2.10960733e-02, 3.13841036e-01, 2.30356743e+00, 3.38064138e-02])

In [ ]:
np.round_(fit.scores_)

array([  1.,  12.,   2.,  64.,   0., 487., 223.,   0.,   0.,   0.,   2.,
         0.])

In [ ]:
chi = pd.Series(fit.scores_)
chi.index = X.columns
chi.sort_values(ascending=False)

free sulfur dioxide     486.716943
total sulfur dioxide    222.820658
residual sugar           64.218079
volatile acidity         11.855239
alcohol                   2.303567
citric acid               1.643697
fixed acidity             0.718728
sulphates                 0.313841
chlorides                 0.169352
type                      0.033806
pH                        0.021096
density                   0.000016
dtype: float64

In [ ]:
X_new=test.fit_transform(X, y)

In [ ]:
X_new

array([[  0.7 ,   1.9 ,  11.  ,  34.  ],
       [  0.88,   2.6 ,  25.  ,  67.  ],
       [  0.76,   2.3 ,  15.  ,  54.  ],
       ...,
       [  0.24,   1.2 ,  30.  , 111.  ],
       [  0.29,   1.1 ,  20.  , 110.  ],
       [  0.21,   0.8 ,  22.  ,  98.  ]])

more info : https://www.youtube.com/watch?v=6gHUIdGh2-Y

syarat menggunakaan chi square 
- dataset harus numerik semua
- no negative value
- categorical harus di label encoder terlebih dahulu
- hanya bisa digunakan untuk target yang categorical

## Feature Selection Mutual Info Classifiers

In [ ]:
from sklearn.feature_selection import mutual_info_classif
# determine the mutual information
mutual_info = mutual_info_classif(X, y)
mutual_info

array([0.00443924, 0.00848431, 0.00405101, 0.00474204, 0.00485136,
       0.01671724, 0.00703904, 0.00127726, 0.0016478 , 0.00085186,
       0.00401896, 0.        ])

In [ ]:
mutual_info = pd.Series(mutual_info)
mutual_info.index = X.columns
mutual_info.sort_values(ascending=False)

free sulfur dioxide     0.016717
volatile acidity        0.008484
total sulfur dioxide    0.007039
chlorides               0.004851
residual sugar          0.004742
fixed acidity           0.004439
citric acid             0.004051
alcohol                 0.004019
pH                      0.001648
density                 0.001277
sulphates               0.000852
type                    0.000000
dtype: float64

## Feature Selection Mutual Information for Regression

In [ ]:
housing_df = pd.read_csv('/content/Ames_Housing_Data.csv')

In [ ]:
housing_df.head()

PID  MS SubClass MS Zoning  Lot Frontage  Lot Area Street Alley  \
0  526301100           20        RL         141.0     31770   Pave   NaN   
1  526350040           20        RH          80.0     11622   Pave   NaN   
2  526351010           20        RL          81.0     14267   Pave   NaN   
3  526353030           20        RL          93.0     11160   Pave   NaN   
4  527105010           60        RL          74.0     13830   Pave   NaN   

  Lot Shape Land Contour Utilities  ... Pool Area Pool QC  Fence Misc Feature  \
0       IR1          Lvl    AllPub  ...         0     NaN    NaN          NaN   
1       Reg          Lvl    AllPub  ...         0     NaN  MnPrv          NaN   
2       IR1          Lvl    AllPub  ...         0     NaN    NaN         Gar2   
3       Reg          Lvl    AllPub  ...         0     NaN    NaN          NaN   
4       IR1          Lvl    AllPub  ...         0     NaN  MnPrv          NaN   

  Misc Val Mo Sold Yr Sold  Sale Type  Sale Condition  SalePrice  
0        0       5    2010        WD           Normal     215000  
1        0       6    2010        WD           Normal     105000  
2    12500       6    2010        WD           Normal     172000  
3        0       4    2010        WD           Normal     244000  
4        0       3    2010        WD           Normal     189900  

[5 rows x 81 columns]

In [ ]:
numerical_cols = housing_df.select_dtypes(include=np.number).columns.tolist()

In [ ]:
housing_df=housing_df[numerical_cols]

In [ ]:
housing_df=housing_df.drop("PID",axis=1)

In [ ]:
X1 = housing_df.drop(labels=['SalePrice'], axis=1)
y1 = housing_df['SalePrice']

In [ ]:
from sklearn.feature_selection import mutual_info_regression
mutual_info = mutual_info_regression(X1.fillna(0), y1)
mutual_info

array([0.28412811, 0.23414664, 0.16934053, 0.58326498, 0.11778104,
       0.40083755, 0.29416054, 0.15714659, 0.17621354, 0.        ,
       0.11596309, 0.39080127, 0.36939296, 0.20866237, 0.00174772,
       0.49683856, 0.04354694, 0.01926054, 0.25640593, 0.07818586,
       0.04279342, 0.01386709, 0.19972328, 0.18148434, 0.32133372,
       0.38962942, 0.41653209, 0.10732342, 0.17819222, 0.05380684,
       0.        , 0.01768386, 0.00336698, 0.00352604, 0.        ,
       0.04182793])

In [ ]:
mutual_info = pd.Series(mutual_info)
mutual_info.index = X1.columns
mutual_info.sort_values(ascending=False)

Overall Qual       0.583265
Gr Liv Area        0.496839
Garage Area        0.416532
Year Built         0.400838
Total Bsmt SF      0.390801
Garage Cars        0.389629
1st Flr SF         0.369393
Garage Yr Blt      0.321334
Year Remod/Add     0.294161
MS SubClass        0.284128
Full Bath          0.256406
Lot Frontage       0.234147
2nd Flr SF         0.208662
TotRms AbvGrd      0.199723
Fireplaces         0.181484
Open Porch SF      0.178192
BsmtFin SF 1       0.176214
Lot Area           0.169341
Mas Vnr Area       0.157147
Overall Cond       0.117781
Bsmt Unf SF        0.115963
Wood Deck SF       0.107323
Half Bath          0.078186
Enclosed Porch     0.053807
Bsmt Full Bath     0.043547
Bedroom AbvGr      0.042793
Yr Sold            0.041828
Bsmt Half Bath     0.019261
Screen Porch       0.017684
Kitchen AbvGr      0.013867
Misc Val           0.003526
Pool Area          0.003367
Low Qual Fin SF    0.001748
BsmtFin SF 2       0.000000
3Ssn Porch         0.000000
Mo Sold            0

## ANOVA f-test statistic

In [ ]:
from sklearn.feature_selection import f_classif
from sklearn.feature_selection import SelectKBest
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1)

In [ ]:
f_test = SelectKBest(score_func=f_classif, k=4)
fit = f_test.fit(X, y)
fit.scores_

array([3.08644096e+00, 1.52016610e+02, 2.48925411e+01, 1.54763350e+01,
       7.73964554e+00, 4.74970744e+01, 8.08158370e+00, 1.73699673e+00,
       2.62700596e+00, 7.53737820e+00, 1.70314036e+01, 1.37321639e-01])

In [ ]:
np.round_(fit.scores_)

array([  3., 152.,  25.,  15.,   8.,  47.,   8.,   2.,   3.,   8.,  17.,
         0.])

In [ ]:
result = pd.Series(fit.scores_)
result.index = X.columns
result.sort_values(ascending=False)

volatile acidity        152.016610
free sulfur dioxide      47.497074
citric acid              24.892541
alcohol                  17.031404
residual sugar           15.476335
total sulfur dioxide      8.081584
chlorides                 7.739646
sulphates                 7.537378
fixed acidity             3.086441
pH                        2.627006
density                   1.736997
type                      0.137322
dtype: float64

more info : https://machinelearningmastery.com/feature-selection-with-numerical-input-data/