# Non Graded Challenge 4

## Description

This Non-Graded Assignment was created to evaluate the concept of Linear Algebra as follows:

- Understand the concept of Scalar and Vectors
- Able to create Scalar and Vector in Python
- Able to apply arithmetic operations to Scalar and Vector

Create the following vector in Python:

  $$
  \begin{bmatrix}
  17 \\
  22 \\
  19
  \end{bmatrix}
  $$

Given 3 vectors in 3 dimension:
$$
A=
\begin{bmatrix}
17 \\
22 \\
19
\end{bmatrix}
,B=
\begin{bmatrix}
10 \\
20 \\
11
\end{bmatrix},
C=
\begin{bmatrix}
5 \\
12 \\
9
\end{bmatrix}
$$

Calculate:
   - A+B
   - B-C
   - A dot C
   - A x B
   - norm A
   - Angle between vectors A and B

- Plot the following vectors onto a 2D plane:

  $$
  U =
  \begin{bmatrix}
  2 \\ 5
  \end{bmatrix},
  V =
  \begin{bmatrix}
  3 \\ 1
  \end{bmatrix}
  $$

## WORKSPACE

Import libraries that we are going to use.

In [2]:
import numpy as np

In [6]:
A = np.array([
    [17],
    [22],
    [19]
])

B = np.array([
    [10],
    [20],
    [11]
])

C = np.array([
    [5],
    [12],
    [9]
])


In [7]:
A + B

array([[27],
       [42],
       [30]])

In [8]:
B - C

array([[5],
       [8],
       [2]])

In [9]:
A @ C

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 1)

In [10]:
A * B

array([[170],
       [440],
       [209]])