In [1]:
import numpy as np

In [3]:
a = np.array([[1,2],[8,9]])

a

array([[1, 2],
       [8, 9]])

In [9]:
from numpy.linalg import inv, det

In [7]:
invA = inv(a)

invA

array([[-1.28571429,  0.28571429],
       [ 1.14285714, -0.14285714]])

In [10]:
det(a)

-6.999999999999998

In [8]:
a @ invA

array([[1.0000000e+00, 0.0000000e+00],
       [4.4408921e-16, 1.0000000e+00]])

In [11]:
from numpy.linalg import eig

In [12]:
A = np.array([[1,2],[2,4]])

eigval, eigvec = eig(A)

In [13]:
eigval

array([0., 5.])

In [14]:
eigvec

array([[-0.89442719, -0.4472136 ],
       [ 0.4472136 , -0.89442719]])

In [16]:
from numpy import diag

In [18]:
diag(eigval)

array([[0., 0.],
       [0., 5.]])

In [19]:
eigvec @ diag(eigval) @ inv(eigvec)

array([[1., 2.],
       [2., 4.]])

In [21]:
from numpy.linalg import eig

In [49]:
np.random.seed(1)
A = np.array([[0,0,0,0,1/2,0],
            [1/4,0,0,0,0,0],
            [0,1/2,0,0,0,0],
            [1/4,1/2,0,0,1/2,0],
            [1/4,0,1,1,0,1],
            [1/4,0,0,0,0,0]])

A

array([[0.  , 0.  , 0.  , 0.  , 0.5 , 0.  ],
       [0.25, 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.5 , 0.  , 0.  , 0.  , 0.  ],
       [0.25, 0.5 , 0.  , 0.  , 0.5 , 0.  ],
       [0.25, 0.  , 1.  , 1.  , 0.  , 1.  ],
       [0.25, 0.  , 0.  , 0.  , 0.  , 0.  ]])

In [54]:
eigval, eigvec = eig(A.T)

In [53]:
eigval

array([ 1.00000000e+00+0.j        , -1.39845075e-01+0.39240258j,
       -1.39845075e-01-0.39240258j, -7.20309850e-01+0.j        ,
        6.27089983e-17+0.j        , -2.02451367e-17+0.j        ])

In [56]:
eigval[0]

(1.0000000000000002+0j)

In [55]:
np.argmax(eigvec[0])

4

In [38]:
eigval[3]

(-0.440136223137077-0.5633077587687763j)

In [39]:
eigvec[3]

array([ 0.26838145+0.j        , -0.03280276+0.j        ,
       -0.24243408+0.28859748j, -0.24243408-0.28859748j,
        0.1767767 +0.j        , -0.58530969+0.j        ])

In [40]:
eigvec[4]

array([ 0.6459704 +0.j, -0.43313172+0.j,  0.740891  +0.j,  0.740891  -0.j,
       -0.1767767 +0.j,  0.3291388 +0.j])

In [4]:
import numpy as np
np.random.seed(3)



In [6]:
np.random.random()

0.7081478226181048

In [7]:
np.random.random()

0.2909047389129443